server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_tutor_dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev@example.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
