export const styles = {
  layout: {
    container: 'bg-surface font-body-md text-on-surface antialiased min-h-screen selection:bg-secondary-container selection:text-on-secondary-container',
    main: 'w-full pt-16 bg-surface min-h-screen',
    mainInner: 'flex flex-col w-full',
    contentWrapper: 'relative w-full min-h-[calc(100vh-4rem)] flex items-center justify-center p-space-md sm:p-gutter lg:p-margin overflow-hidden',
    card: 'relative z-10 w-full max-w-lg bg-surface-container-lowest/95 backdrop-blur-md shadow-xl rounded-xl p-space-lg sm:p-space-xl border border-outline-variant/30',
  },
  header: {
    wrapper: 'fixed top-0 left-0 w-full z-50 bg-surface/80 backdrop-blur-md border-b border-outline-variant/30',
    inner: 'h-16 max-w-7xl mx-auto px-margin flex items-center justify-between',
    logoLink: 'flex items-center gap-space-sm cursor-pointer',
    logoImg: 'h-7 w-auto object-contain',
    logoText: 'font-headline-lg text-base font-semibold tracking-tight text-on-surface flex items-center gap-space-xs',
    logoDot: 'h-1.5 w-1.5 rounded-full bg-primary inline-block',
    nav: 'flex items-center gap-space-md text-sm',
    navLink: 'text-on-surface-variant hover:text-on-surface transition-colors flex items-center gap-space-xs',
  },
  form: {
    wrapper: 'space-y-space-md',
    field: 'block font-label-sm text-label-sm font-semibold text-on-surface mb-1.5',
    inputWrapper: 'relative flex items-center',
    inputIcon: 'material-symbols-outlined absolute left-3.5 text-on-surface-variant text-[20px] pointer-events-none',
    input: (hasError: boolean) => `w-full pl-11 pr-4 py-3 bg-surface-container-low focus:bg-surface-container-lowest rounded-lg font-body-md text-body-md text-on-surface placeholder:text-outline focus:outline-none focus:ring-2 focus:ring-primary shadow-sm transition-all border ${hasError ? 'border-error ring-1 ring-error' : 'border-outline-variant/30'}`,
    inputPassword: (hasError: boolean) => `w-full pl-11 pr-11 py-3 bg-surface-container-low focus:bg-surface-container-lowest rounded-lg font-body-md text-body-md text-on-surface placeholder:text-outline focus:outline-none focus:ring-2 focus:ring-primary shadow-sm transition-all border ${hasError ? 'border-error ring-1 ring-error' : 'border-outline-variant/30'}`,
    togglePasswordBtn: 'absolute right-3 p-1 rounded hover:bg-surface-container text-on-surface-variant hover:text-on-surface transition-colors focus:outline-none',
    errorText: 'mt-1 text-xs text-error font-medium',
    rememberWrapper: 'flex items-center gap-space-sm cursor-pointer select-none',
    checkbox: 'w-4 h-4 rounded border-outline-variant bg-surface-container-low text-primary focus:ring-primary cursor-pointer',
    rememberText: 'font-label-sm text-label-sm text-on-surface-variant',
    submitBtn: 'w-full mt-space-sm py-3 px-space-md bg-primary hover:bg-primary-container text-on-primary font-body-md font-semibold rounded-lg shadow-md hover:shadow-lg transition-all flex items-center justify-center gap-space-sm disabled:opacity-70 disabled:cursor-not-allowed',
    forgotPassword: 'font-label-sm text-label-sm font-medium text-primary hover:text-on-primary-fixed-variant transition-colors',
  },
  auth: {
    titleWrapper: 'flex flex-col items-center text-center mb-space-lg',
    iconWrapper: 'w-12 h-12 rounded-xl bg-primary flex items-center justify-center text-on-primary shadow-sm mb-space-sm',
    successIconWrapper: 'w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center text-primary mb-space-sm',
    title: 'font-headline-lg text-headline-lg text-on-surface tracking-tight mb-1.5',
    subtitle: 'font-body-md text-body-md text-on-surface-variant max-w-sm',
    googleBtn: 'w-full flex items-center justify-center gap-space-sm py-3 px-space-md bg-surface-container-low hover:bg-surface-container transition-all duration-200 rounded-lg shadow-sm group border border-outline-variant/30',
    googleBtnText: 'font-label-sm text-body-md font-medium text-on-surface group-hover:text-primary transition-colors',
    dividerWrapper: 'relative my-space-lg flex items-center justify-center',
    dividerLine: 'w-full h-px bg-surface-container-highest',
    dividerText: 'absolute px-space-sm bg-surface-container-lowest text-label-sm font-label-sm text-on-surface-variant uppercase tracking-wider',
    alertError: 'p-3 bg-error-container text-on-error-container rounded-lg text-sm font-medium',
    footer: 'pt-space-lg text-center border-t border-outline-variant/20 mt-space-lg',
    footerText: 'font-body-md text-label-sm text-on-surface-variant',
    registerLink: 'font-semibold text-primary hover:text-on-primary-fixed-variant transition-colors ml-1',
  },
  session: {
    infoBox: 'bg-surface-container p-space-md rounded-lg mb-space-lg flex flex-col gap-space-xs text-sm',
    infoRow: 'flex justify-between',
    infoLabel: 'text-on-surface-variant font-medium',
    infoValue: 'text-on-surface font-semibold',
    logoutBtn: 'w-full flex justify-center py-3 px-space-md border border-outline-variant text-on-surface font-semibold rounded-lg hover:bg-surface-container transition-colors',
  }
};
