export const styles = {
  page: 'max-w-3xl mx-auto space-y-5',
  card: 'bg-surface-container-lowest rounded-2xl border border-outline-variant p-6 md:p-8 shadow-sm space-y-5',
  eyebrow: 'inline-flex items-center gap-1.5 text-primary text-xs font-semibold uppercase tracking-wide',
  title: 'text-2xl md:text-3xl font-bold text-on-surface',
  meta: 'flex flex-wrap gap-2',
  chip: 'px-3 py-1 rounded-full bg-surface-container text-on-surface-variant text-xs font-medium',
  body: 'text-sm md:text-base text-on-surface leading-relaxed',
  sectionTitle: 'font-bold text-on-surface',
  outline: 'space-y-3',
  outlineItem: 'flex gap-3 text-sm text-on-surface',
  outlineIndex: 'w-6 h-6 shrink-0 rounded-full bg-primary text-on-primary text-xs font-bold flex items-center justify-center',
  topics: 'flex flex-wrap gap-2',
  topic: 'px-3 py-1 rounded-full bg-primary-fixed/40 text-primary text-xs font-semibold',
  back: 'inline-flex items-center gap-1 text-sm font-semibold text-primary hover:underline',
  error: 'bg-surface-container-lowest rounded-2xl border border-outline-variant p-8 text-center space-y-3',
  errorTitle: 'text-lg font-bold text-on-surface',
  errorBody: 'text-sm text-on-surface-variant',
}
