export const styles = {
  container: 'space-y-6',
  breadcrumbWrapper: 'space-y-3',
  breadcrumb: 'flex items-center gap-2 text-label-sm font-label-sm text-on-surface-variant',
  breadcrumbLink: 'hover:text-primary transition-colors',
  breadcrumbIcon: 'material-symbols-outlined text-xs',
  breadcrumbActive: 'text-primary font-semibold',
  headerSection: 'flex flex-col lg:flex-row items-start lg:items-center justify-between gap-space-lg relative z-10',
  profileCard: 'flex flex-col sm:flex-row items-center sm:items-start gap-space-lg text-center sm:text-left w-full lg:w-auto',
  avatarWrapper: 'relative group',
  avatarImageWrapper: 'w-24 h-24 sm:w-28 sm:h-28 rounded-2xl overflow-hidden shadow-md bg-surface-container-low relative',
  avatarImage: 'w-full h-full object-cover',
  editAvatarBtn: 'absolute -bottom-1.5 -right-1.5 w-8 h-8 rounded-full bg-primary text-on-primary flex items-center justify-center shadow-md hover:bg-primary-container transition-transform active:scale-95',
  profileInfo: 'flex flex-col gap-1.5',
  nameRow: 'flex flex-wrap items-center justify-center sm:justify-start gap-space-xs',
  name: 'font-headline-lg text-[22px] sm:text-[26px] font-bold text-on-surface tracking-tight',
  verifiedIcon: 'material-symbols-outlined text-primary text-[20px]',
  schoolYearBadge: 'px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant font-label-sm text-[11px] font-semibold flex items-center gap-1',
  detailsRow: 'flex flex-wrap items-center justify-center sm:justify-start gap-x-space-md gap-y-1 text-on-surface-variant font-label-sm text-label-sm',
  detailItem: 'flex items-center gap-1',
  emailRow: 'flex items-center justify-center sm:justify-start gap-1.5 text-on-surface-variant font-label-sm text-[12px] pt-1',
  emailText: 'font-medium text-on-surface',
  actionSection: 'flex items-center gap-space-sm w-full lg:w-auto justify-end',
  actionBtnPrimary: 'w-full sm:w-auto px-space-lg py-2.5 rounded-xl bg-primary text-on-primary font-label-sm text-label-sm font-semibold shadow-sm hover:bg-primary-container transition-all flex items-center justify-center gap-space-xs',
  actionBtnSecondary: 'px-space-md py-2.5 rounded-xl bg-surface-container-high text-on-surface font-label-sm text-label-sm font-semibold hover:bg-surface-container-highest transition-colors',
  bentoGrid: 'grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-space-md mt-space-lg pt-space-lg',
  bentoCard: 'p-space-md rounded-xl flex flex-col justify-between gap-space-xs',
  bentoCardDefault: 'bg-surface-container-low',
  bentoCardHighlight: 'bg-tertiary-fixed/40',
  bentoHeader: 'flex items-center justify-between',
  bentoTitle: 'font-label-sm text-label-sm font-medium',
  bentoTitleDefault: 'text-on-surface-variant',
  bentoTitleHighlight: 'text-on-tertiary-fixed',
  bentoIconWrapper: 'w-7 h-7 rounded-lg flex items-center justify-center',
  bentoIconPrimary: 'bg-primary-fixed text-primary',
  bentoIconSecondary: 'bg-secondary-fixed text-on-secondary-fixed-variant',
  bentoIconTertiary: 'bg-tertiary-fixed text-tertiary',
  bentoIconNeutral: 'bg-surface-container-highest text-on-surface-variant',
  bentoValue: 'font-headline-lg font-bold',
  bentoValueDefault: 'text-[22px] text-on-surface',
  bentoValueSmall: 'text-[20px] text-on-surface',
  bentoValueHighlight: 'text-[22px] text-tertiary',
  bentoValueMedium: 'text-[18px] text-on-surface',
  bentoSubtitle: 'font-label-sm font-semibold',
  bentoSubtitleSecondary: 'text-[13px] text-secondary',
  bentoSubtitleHighlight: 'text-[12px] text-on-tertiary-fixed',
  bentoSubtitleNeutral: 'text-[13px] text-on-surface-variant',
  bentoFooter: 'font-label-sm text-[11px]',
  bentoFooterPrimary: 'text-primary font-semibold',
  bentoFooterSecondary: 'text-secondary font-medium',
  bentoFooterHighlight: 'text-on-tertiary-fixed-variant',
  progressBarTrack: 'w-full bg-surface-container-highest rounded-full h-1.5 mt-2 overflow-hidden',
  progressBarFill: 'bg-primary h-1.5 rounded-full',
  mainContentGrid: 'grid grid-cols-1 lg:grid-cols-12 gap-space-lg',
  mainColumn: 'lg:col-span-6 flex flex-col gap-space-lg',
  card: 'p-space-lg rounded-xl bg-surface-container-lowest shadow-sm flex flex-col gap-space-md',
  cardHeader: 'flex items-center justify-between pb-space-sm',
  cardTitleWrapper: 'flex items-center gap-space-xs',
  cardIconWrapper: 'w-8 h-8 rounded-lg flex items-center justify-center',
  cardIconPrimary: 'bg-primary-fixed text-primary',
  cardIconSecondary: 'bg-secondary-container text-on-secondary-container',
  cardTitle: 'font-headline-lg text-[18px] font-bold text-on-surface',
  cardBadge: 'font-label-sm text-[11px] font-semibold px-2.5 py-1 rounded-md',
  cardBadgeSecondary: 'text-secondary bg-surface-container',
  cardBadgePrimary: 'text-primary bg-primary-fixed',
  infoRowContainer: 'flex flex-col gap-space-md',
  infoRow: 'flex items-start justify-between p-space-sm rounded-lg bg-surface-container-low',
  infoRowCol: 'flex flex-col',
  infoLabel: 'font-label-sm text-[12px] text-on-surface-variant',
  infoValue: 'font-body-md text-[15px] font-semibold text-on-surface',
  infoValueSmall: 'font-body-md text-[14px] font-semibold text-on-surface',
  infoDesc: 'font-label-sm text-[11px] text-secondary mt-0.5',
  infoIcon: 'material-symbols-outlined text-[18px] text-on-surface-variant mt-1',
  infoGrid: 'grid grid-cols-2 gap-space-sm',
  infoGridItem: 'p-space-sm rounded-lg bg-surface-container-low flex flex-col',
  banner: 'p-space-lg rounded-xl bg-surface-container-lowest shadow-sm flex items-center justify-between gap-space-md',
  bannerLeft: 'flex items-center gap-space-md',
  bannerIconWrapper: 'w-12 h-12 rounded-xl bg-secondary-fixed flex items-center justify-center text-on-secondary-fixed',
  bannerTitle: 'font-headline-lg text-[15px] font-bold text-on-surface',
  bannerSubtitle: 'font-label-sm text-[12px] text-on-surface-variant',
  chipContainer: 'flex flex-wrap gap-space-xs mt-1',
  chip: 'px-3 py-1 rounded-full bg-surface-container-lowest text-primary font-label-sm text-label-sm font-semibold shadow-sm flex items-center gap-1.5',
  goalBanner: 'flex items-center justify-between p-space-md rounded-lg bg-surface-container-low',
  goalLeft: 'flex items-center gap-space-md',
  goalIconWrapper: 'w-10 h-10 rounded-xl bg-surface-container-lowest flex items-center justify-center text-secondary shadow-sm',
  preferenceCard: 'p-space-md rounded-lg bg-surface-container-low flex flex-col gap-2',
  preferenceItem: 'p-space-sm rounded-lg bg-surface-container-lowest shadow-sm flex items-center gap-space-sm',
  preferenceIconWrapper: 'w-8 h-8 rounded-lg bg-primary text-on-primary flex items-center justify-center shrink-0',
  quickActionWrapper: 'mt-auto pt-space-xs flex justify-end',
  quickActionLink: 'text-primary hover:text-primary-container font-label-sm text-label-sm font-semibold flex items-center gap-1 transition-colors',
  editBanner: 'w-full rounded-xl bg-primary-fixed/30 p-space-md flex flex-col sm:flex-row sm:items-center justify-between gap-space-md',
  editBannerLeft: 'flex items-center gap-space-md',
  editBannerIconWrapper: 'w-9 h-9 rounded-full bg-primary text-on-primary flex items-center justify-center shrink-0',
  editBannerTitle: 'font-headline-lg text-[15px] font-semibold text-on-surface',
  editBannerDesc: 'font-label-sm text-[13px] text-secondary',
  formGroup: 'flex flex-col gap-1.5',
  formLabel: 'font-label-sm text-label-sm font-semibold text-on-surface flex items-center gap-1',
  formInput: 'w-full px-space-md py-2.5 rounded-xl bg-surface-container-low text-on-surface font-body-md text-[15px] focus:outline-none focus:bg-surface-container-lowest focus:shadow-md transition-all',
  formSelect: 'w-full appearance-none px-space-md py-2.5 rounded-xl bg-surface-container-low text-on-surface font-body-md text-[15px] focus:outline-none focus:bg-surface-container-lowest focus:shadow-md transition-all cursor-pointer',
  formHint: 'font-label-sm text-[11px] text-on-surface-variant',
  formActionGroup: 'flex items-center justify-end gap-space-sm pt-space-md',
  stepper: 'flex items-center gap-space-md p-space-sm rounded-xl bg-surface-container-low w-fit',
  stepperBtn: 'w-9 h-9 rounded-lg bg-surface-container-lowest text-on-surface flex items-center justify-center font-bold shadow-sm hover:bg-surface-container transition-transform active:scale-95',
  readOnlyCard: 'p-space-lg rounded-xl bg-surface-container-low shadow-sm flex flex-col gap-space-md',
  readOnlyHeader: 'flex items-center gap-space-xs pb-space-xs',
  readOnlyTitle: 'font-headline-lg text-[16px] font-bold text-on-surface',
  readOnlyDesc: 'font-label-sm text-[12px] text-on-surface-variant leading-relaxed',
  readOnlyItem: 'p-space-sm rounded-lg bg-surface-container-lowest/80 flex items-center justify-between',
  readOnlyBadge: 'flex items-center gap-1 text-[11px] text-secondary font-medium bg-surface-container px-2 py-1 rounded',
  supportNote: 'p-space-sm rounded-lg bg-surface-container flex items-center gap-space-sm mt-2',
};
