export const styles = {
  header: 'sticky top-0 z-40 border-b border-outline-variant/30 bg-surface/85 backdrop-blur-xl shadow-sm transition-all',
  container: 'flex justify-between items-center w-full px-space-md md:px-space-lg max-w-[1680px] mx-auto h-16',
  navGroup: 'flex items-center gap-6 lg:gap-8',
  logoLink: 'flex items-center gap-3 text-primary font-headline-lg text-headline-lg font-semibold tracking-tight cursor-pointer',
  navLinks: 'hidden md:flex items-center gap-1 lg:gap-2 ml-4',
  navLink: 'text-on-surface-variant hover:text-primary hover:bg-primary/5 rounded-lg px-3 py-2 font-medium transition-all duration-200 text-sm',
  navLinkActive: 'text-primary bg-primary/10 font-bold px-3 py-2 rounded-lg text-sm shadow-sm',
  mobileMenu: 'absolute top-[65px] left-0 right-0 bg-surface-container-lowest border-b border-outline-variant shadow-lg md:hidden flex flex-col z-50',
  mobileMenuItem: 'px-6 py-4 border-b border-outline-variant/30 text-on-surface hover:bg-surface-container-low transition-colors font-medium',
  mobileMenuItemActive: 'px-6 py-4 border-b border-outline-variant/30 text-primary bg-primary-fixed/10 font-bold',
  actionGroup: 'flex items-center gap-3',
  streakBadge: 'hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-surface-container rounded-full text-on-surface text-label-sm font-label-sm border border-outline-variant',
  streakIcon: 'material-symbols-outlined text-amber-500',
  streakCount: 'font-bold text-on-surface',
  streakLabel: 'text-on-surface-variant text-xs',
  xpBadge: 'hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-primary-fixed rounded-full text-on-primary-fixed text-label-sm font-label-sm font-semibold',
  xpIcon: 'material-symbols-outlined text-primary',
  notificationBtn: 'relative p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container rounded-full transition',
  notificationDot: 'absolute top-1.5 right-1.5 w-2 h-2 bg-error rounded-full ring-2 ring-surface-container-lowest',
  scannerBtn: 'hidden lg:flex items-center gap-1.5 px-3.5 py-1.5 bg-primary text-on-primary hover:bg-primary-container rounded-lg font-label-sm text-label-sm font-semibold shadow-sm transition active:scale-95',
  scannerIcon: 'material-symbols-outlined text-sm',
  profileChipWrapper: 'relative',
  profileChip: 'flex items-center gap-2 pl-2 border-l border-outline-variant cursor-pointer hover:bg-surface-container/50 py-1 pr-1 rounded transition-colors',
  profileAvatar: 'w-9 h-9 rounded-full object-cover ring-2 ring-primary-fixed',
  profileInfo: 'hidden xl:block text-left',
  profileName: 'font-semibold text-xs leading-none text-on-surface',
  profileClass: 'text-[11px] text-on-surface-variant font-medium mt-0.5',
  dropdownMenu: 'absolute right-0 top-full mt-2 w-48 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-lg py-1.5 z-50 flex flex-col overflow-hidden',
  dropdownItem: 'flex items-center gap-2.5 px-4 py-2.5 text-sm text-on-surface hover:bg-surface-container-high transition-colors text-left w-full cursor-pointer',
  dropdownIcon: 'material-symbols-outlined text-[20px] text-on-surface-variant',
  dropdownDivider: 'h-px w-full bg-outline-variant/50 my-1',
  notificationDropdownMenu: 'absolute right-0 top-full mt-2 w-80 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-lg py-2 z-50 flex flex-col',
  notificationHeader: 'flex justify-between items-center px-4 py-2 border-b border-outline-variant',
  notificationTitle: 'font-semibold text-on-surface text-sm',
  notificationMarkAllBtn: 'text-primary hover:text-primary-hover text-xs font-medium cursor-pointer',
  notificationList: 'max-h-80 overflow-y-auto flex flex-col',
  notificationItem: 'flex flex-col gap-1 px-4 py-3 hover:bg-surface-container-high transition-colors cursor-pointer border-b border-outline-variant/50 last:border-0 relative',
  notificationItemUnread: 'bg-primary-container/20',
  notificationUnreadDot: 'absolute top-3 left-2 w-2 h-2 bg-primary rounded-full',
  notificationItemTitle: 'font-medium text-sm text-on-surface ml-3',
  notificationItemMessage: 'text-xs text-on-surface-variant ml-3 line-clamp-2',
  notificationItemTime: 'text-[10px] text-on-surface-variant ml-3 mt-1',
  notificationEmpty: 'px-4 py-8 text-center text-sm text-on-surface-variant flex flex-col items-center gap-2',
  notificationEmptyIcon: 'material-symbols-outlined text-4xl text-outline-variant'
};
