export const styles = {
  header: 'sticky top-0 z-40 bg-surface-container-lowest shadow-sm border-b border-outline-variant',
  container: 'flex justify-between items-center w-full px-space-md md:px-space-lg max-w-7xl mx-auto h-16',
  navGroup: 'flex items-center gap-8',
  logoLink: 'flex items-center gap-2 text-primary font-headline-lg text-headline-lg font-semibold tracking-tight',
  logoIconWrapper: 'w-9 h-9 rounded-lg bg-primary flex items-center justify-center text-on-primary shadow-sm',
  logoIcon: 'material-symbols-outlined',
  logoText: 'text-xl font-bold tracking-tight',
  navLinks: 'hidden md:flex items-center gap-6',
  navLink: 'text-on-surface-variant hover:text-primary font-medium py-2 transition-colors duration-150',
  navLinkActive: 'border-b-2 border-primary text-primary font-semibold py-2',
  actionGroup: 'flex items-center gap-3',
  streakBadge: 'hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-surface-container rounded-full text-on-surface text-label-sm font-label-sm border border-outline-variant',
  streakIcon: 'material-symbols-outlined text-amber-500',
  streakCount: 'font-bold text-on-surface',
  streakLabel: 'text-on-surface-variant text-xs',
  xpBadge: 'hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-primary-fixed rounded-full text-on-primary-fixed text-label-sm font-label-sm font-semibold',
  xpIcon: 'material-symbols-outlined text-primary',
  notificationBtn: 'relative p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container rounded-full transition',
  notificationDot: 'absolute top-1.5 right-1.5 w-2 h-2 bg-error rounded-full ring-2 ring-surface-container-lowest',
  scannerBtn: 'hidden lg:flex items-center gap-1.5 px-3.5 py-1.5 bg-primary text-on-primary hover:bg-primary-container rounded-lg font-label-sm text-label-sm font-semibold shadow-sm transition active:scale-95',
  scannerIcon: 'material-symbols-outlined text-sm',
  profileChipWrapper: 'relative',
  profileChip: 'flex items-center gap-2 pl-2 border-l border-outline-variant cursor-pointer hover:bg-surface-container/50 py-1 pr-1 rounded transition-colors',
  profileAvatar: 'w-9 h-9 rounded-full object-cover ring-2 ring-primary-fixed',
  profileInfo: 'hidden xl:block text-left',
  profileName: 'font-semibold text-xs leading-none text-on-surface',
  profileClass: 'text-[11px] text-on-surface-variant font-medium mt-0.5',
  dropdownMenu: 'absolute right-0 top-full mt-2 w-48 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-lg py-1.5 z-50 flex flex-col overflow-hidden',
  dropdownItem: 'flex items-center gap-2.5 px-4 py-2.5 text-sm text-on-surface hover:bg-surface-container-high transition-colors text-left w-full cursor-pointer',
  dropdownIcon: 'material-symbols-outlined text-[20px] text-on-surface-variant',
  dropdownDivider: 'h-px w-full bg-outline-variant/50 my-1'
};
