export const styles = {
  layout: {
    container: 'bg-surface font-body-md text-on-surface antialiased min-h-screen selection:bg-secondary-container selection:text-on-secondary-container',
    main: 'w-full pt-16 bg-surface min-h-screen',
    mainInner: 'flex flex-col w-full',
    contentWrapper: 'relative w-full overflow-hidden py-10 px-margin flex items-center justify-center min-h-[calc(100vh-4rem)]',
    card: 'w-full max-w-xl bg-surface-container-lowest rounded-xl p-8 sm:p-10 shadow-md flex flex-col justify-between relative z-10 border border-outline-variant/30',
  },
  header: {
    wrapper: 'fixed top-0 left-0 w-full z-50 bg-surface/80 backdrop-blur-md border-b border-outline-variant/30',
    inner: 'h-16 max-w-7xl mx-auto px-margin flex items-center justify-between',
    logoLink: 'flex items-center gap-space-sm cursor-pointer',
    logoImg: 'h-7 w-auto object-contain',
    logoText: 'font-headline-lg text-base font-semibold tracking-tight text-on-surface flex items-center gap-space-xs',
    logoDot: 'h-1.5 w-1.5 rounded-full bg-primary inline-block',
    nav: 'flex items-center gap-space-md text-sm',
    navLink: 'text-on-surface-variant hover:text-on-surface transition-colors flex items-center gap-space-xs',
  },
  auth: {
    taglineWrapper: 'flex items-center gap-space-xs mb-3',
    tagline: 'inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-fixed text-on-primary-fixed text-xs font-medium',
    taglineIcon: 'material-symbols-outlined text-[14px]',
    title: 'font-headline-lg text-headline-lg text-on-surface tracking-tight mb-2',
    subtitle: 'font-body-md text-body-md text-on-surface-variant mb-8',
    googleBtn: 'w-full flex items-center justify-center gap-3 py-3 px-4 rounded-lg bg-surface-container-low hover:bg-surface-container transition-colors duration-200 text-on-surface font-medium text-sm shadow-sm cursor-pointer border border-outline-variant/30 group',
    googleBtnText: 'font-label-sm text-body-md font-medium text-on-surface group-hover:text-primary transition-colors',
    dividerWrapper: 'relative my-6 text-center',
    dividerLine: 'absolute inset-0 flex items-center',
    dividerLineInner: 'w-full bg-surface-container-highest h-[1px]',
    dividerText: 'relative bg-surface-container-lowest px-4 text-xs font-medium uppercase tracking-wider text-outline',
    alertError: 'p-3 bg-error-container text-on-error-container rounded-lg text-sm font-medium mb-4',
    footer: 'pt-6 mt-6 border-t border-outline-variant/20 text-center',
    footerText: 'text-sm text-on-surface-variant',
    loginLink: 'text-primary font-semibold hover:underline ml-1 transition-colors',
  },
  form: {
    wrapper: 'space-y-4',
    grid: 'grid grid-cols-1 sm:grid-cols-2 gap-4',
    field: 'block text-xs font-semibold uppercase tracking-wider text-on-surface-variant mb-1.5',
    inputWrapper: 'relative',
    inputIcon: 'material-symbols-outlined absolute left-3.5 top-1/2 -translate-y-1/2 text-outline text-[18px] pointer-events-none',
    input: (hasError: boolean) => `w-full pl-10 pr-4 py-2.5 rounded-lg bg-surface-container-low text-on-surface text-sm placeholder:text-outline focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary transition-all border ${hasError ? 'border-error ring-1 ring-error' : 'border-outline-variant/30'}`,
    inputPassword: (hasError: boolean) => `w-full pl-10 pr-11 py-2.5 rounded-lg bg-surface-container-low text-on-surface text-sm placeholder:text-outline focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary transition-all border ${hasError ? 'border-error ring-1 ring-error' : 'border-outline-variant/30'}`,
    togglePasswordBtn: 'absolute right-3.5 top-1/2 -translate-y-1/2 text-outline hover:text-on-surface transition-colors cursor-pointer',
    errorText: 'mt-1 text-xs text-error font-medium',
    strengthWrapper: 'mt-2 flex items-center gap-1.5',
    strengthBar: (isActive: boolean, colorClass: string) => `h-1 flex-1 rounded-full transition-all duration-300 ${isActive ? colorClass : 'bg-surface-container'}`,
    strengthText: 'text-[11px] font-medium pl-2 w-20 text-right',
    termsWrapper: 'pt-2',
    termsLabel: 'flex items-start gap-3 cursor-pointer group',
    checkbox: 'mt-1 rounded bg-surface-container-low text-primary focus:ring-primary cursor-pointer h-4 w-4 border-outline-variant',
    termsText: 'text-xs text-on-surface-variant leading-relaxed',
    termsLink: 'text-primary font-medium hover:underline',
    submitWrapper: 'pt-3',
    submitBtn: 'w-full py-3.5 px-6 rounded-lg bg-primary hover:bg-primary-container active:scale-[0.99] text-on-primary font-semibold text-sm shadow-md flex items-center justify-center gap-2 transition-all duration-200 cursor-pointer disabled:opacity-70 disabled:cursor-not-allowed disabled:active:scale-100',
  }
};
