export const styles = {
  container: 'space-y-6',
  breadcrumbWrapper: 'space-y-3',
  breadcrumb: 'flex items-center gap-2 text-label-sm font-label-sm text-on-surface-variant',
  breadcrumbLink: 'hover:text-primary transition-colors',
  breadcrumbIcon: 'material-symbols-outlined text-xs',
  breadcrumbActive: 'text-primary font-semibold',
  headerSection: 'flex flex-col lg:flex-row lg:items-center justify-between gap-4',
  title: 'font-headline-lg text-2xl md:text-headline-lg text-on-surface font-bold tracking-tight',
  subtitle: 'text-on-surface-variant text-sm mt-1',
  toolbar: 'flex flex-wrap items-center gap-2.5',
  aiBtn: 'flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-primary to-primary-container text-on-primary rounded-xl font-label-sm text-label-sm font-semibold shadow-md hover:shadow-lg transition transform active:scale-95',
  configBtn: 'flex items-center gap-1.5 px-3.5 py-2.5 bg-surface-container-lowest border border-outline-variant hover:border-primary text-on-surface hover:text-primary rounded-xl font-label-sm text-label-sm font-semibold transition active:scale-95 shadow-sm',
  addBtn: 'flex items-center gap-1.5 px-3.5 py-2.5 bg-surface-container-lowest border border-outline-variant hover:border-primary text-on-surface hover:text-primary rounded-xl font-label-sm text-label-sm font-semibold transition active:scale-95 shadow-sm',
  weekSwitcher: 'flex items-center bg-surface-container-lowest border border-outline-variant rounded-xl p-1 shadow-sm',
  weekBtn: 'p-1.5 hover:bg-surface-container rounded-lg text-on-surface-variant transition',
  weekText: 'px-3 py-1 text-center font-label-sm text-label-sm font-semibold text-on-surface',
  exportBtn: 'flex items-center gap-1.5 px-3 py-2.5 bg-surface-container-lowest border border-outline-variant hover:bg-surface-container rounded-xl text-on-surface-variant font-label-sm text-label-sm transition shadow-sm',
  banner: 'relative overflow-hidden rounded-2xl bg-gradient-to-r from-primary-fixed via-surface-container to-secondary-fixed p-4 md:p-5 border border-outline-variant shadow-sm',
  bannerContent: 'flex flex-col md:flex-row md:items-center justify-between gap-4 relative z-10',
  bannerIconWrapper: 'w-11 h-11 rounded-xl bg-primary text-on-primary flex items-center justify-center flex-shrink-0 shadow-sm',
  bannerStatus: 'inline-flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-primary bg-surface-container-lowest px-2 py-0.5 rounded-full shadow-xs',
  bannerStatusDot: 'w-2 h-2 rounded-full bg-emerald-500 animate-pulse',
  bannerSubtitle: 'text-xs text-on-surface-variant',
  bannerText: 'text-sm font-medium text-on-surface mt-1.5',
  bannerActionGroup: 'flex items-center gap-2.5 flex-shrink-0',
  bannerPrimaryBtn: 'px-4 py-2 bg-primary text-on-primary hover:bg-primary-container text-xs font-semibold rounded-xl transition shadow-sm active:scale-95 flex items-center gap-1.5',
  bannerSecondaryBtn: 'px-3.5 py-2 bg-surface-container-lowest hover:bg-surface-container-high text-on-surface text-xs font-semibold rounded-xl border border-outline-variant transition active:scale-95',
  gridContainer: 'grid grid-cols-1 xl:grid-cols-12 gap-6 items-start',
  tableWrapper: 'xl:col-span-9 bg-surface-container-lowest rounded-2xl border border-outline-variant shadow-sm flex flex-col overflow-hidden custom-scrollbar',
  
  // Settings Panel (Tùy chỉnh số tiết)
  settingsPanel: 'p-4 bg-surface-container-low border-b border-outline-variant',
  settingsHeader: 'flex items-center justify-between mb-4',
  settingsTitleGroup: 'flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-wider',
  settingsCloseBtn: 'text-outline hover:text-on-surface transition',
  settingsGrid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
  settingsCard: 'bg-surface-container-lowest p-4 rounded-xl border border-outline-variant space-y-3',
  settingsCardHeader: 'flex items-center justify-between text-sm font-bold text-on-surface',
  settingsCardHeaderLeft: 'flex items-center gap-2',
  settingsFieldGroup: 'flex gap-3',
  settingsField: 'flex-1 space-y-1',
  settingsLabel: 'text-xs text-on-surface-variant font-medium',
  settingsInput: 'w-full px-3 py-2 bg-surface border border-outline-variant rounded-lg text-sm focus:outline-none focus:border-primary',
  settingsBreak: 'bg-surface-container-low/50 p-3 rounded-lg border border-outline-variant/50 space-y-2 mt-2',
  settingsBreakHeader: 'flex items-center justify-between text-xs font-semibold text-primary',
  settingsFooter: 'flex items-center justify-between mt-4 pt-4 border-t border-outline-variant text-xs',
  settingsFooterText: 'flex items-center gap-1.5 text-on-surface-variant',
  settingsSaveBtn: 'px-4 py-2 bg-primary text-on-primary hover:bg-primary-container text-xs font-semibold rounded-lg shadow-sm transition active:scale-95',
  tableHeader: 'p-4 border-b border-outline-variant flex flex-wrap items-center justify-between gap-3 bg-surface-container-low',
  tableHeaderTitleGroup: 'flex items-center gap-2',
  tableHeaderTitle: 'font-bold text-on-surface text-base',
  tableHeaderActions: 'flex items-center gap-2 flex-wrap',
  table: 'w-full min-w-[920px] border-collapse text-left',
  thBase: 'p-3 text-center border-r border-outline-variant',
  thTime: 'p-3 w-32 border-r border-outline-variant text-center font-bold',
  thToday: 'p-3 w-[13%] text-center border-r-2 border-primary bg-primary-fixed/40 text-primary font-bold relative',
  thTodayBadge: 'absolute -top-0 right-1/2 transform translate-x-1/2 bg-primary text-on-primary text-[10px] px-2 py-0.5 rounded-b-md shadow-xs',
  thTodayDate: 'block text-[11px] font-medium text-primary mt-2',
  thNormalDate: 'block text-[11px] font-normal text-outline',
  tbody: 'divide-y divide-outline-variant text-xs',
  sessionHeaderRow: 'bg-surface-container-high/60 border-y border-outline-variant',
  sessionHeaderCell: 'py-2 px-4 flex items-center justify-between',
  sessionHeaderLeft: 'flex items-center gap-2 font-bold text-xs text-primary',
  sessionHeaderRight: 'flex items-center gap-2',
  timeRow: 'hover:bg-surface/50 transition',
  timeCell: 'p-3 bg-surface-container-low/50 border-r border-outline-variant text-center',
  timeCellTitle: 'font-bold text-on-surface',
  timeCellTime: 'text-[11px] text-on-surface-variant',
  cellBase: 'p-2 border-r border-outline-variant align-top',
  cellToday: 'p-2 border-r-2 border-primary bg-primary-fixed/20 align-top',
  
  // Subject card variations
  cardError: 'group relative rounded-xl p-2.5 bg-error-container/30 border border-error/20 text-on-surface hover:shadow-md transition',
  cardPrimary: 'group relative rounded-xl p-2.5 bg-blue-50 border border-primary/30 text-on-surface hover:shadow-md transition',
  cardPurple: 'rounded-xl p-2.5 bg-purple-50 border border-purple-200 text-on-surface hover:shadow-sm transition',
  cardEmerald: 'rounded-xl p-2.5 bg-emerald-50 border border-emerald-200 text-on-surface hover:shadow-sm transition',
  cardAmber: 'rounded-xl p-2.5 bg-amber-50 border border-amber-200 text-on-surface hover:shadow-sm transition',
  cardSurface: 'rounded-xl p-2.5 bg-surface-container border border-outline-variant text-on-surface hover:shadow-sm transition',
  
  // Badge variations
  badgeError: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-error/10 text-error',
  badgePrimary: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-primary text-on-primary',
  badgePurple: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-purple-100 text-purple-800',
  badgeEmerald: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-emerald-100 text-emerald-800',
  badgeAmber: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-amber-100 text-amber-900',
  badgeSurface: 'inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-surface-container-high text-on-surface-variant',
  
  subjectTitle: 'font-bold text-xs mt-1 text-on-surface',
  subjectDesc: 'text-[11px] text-on-surface-variant',
  
  emptyCell: 'p-2 text-center text-outline-variant bg-surface-container-low/30 align-middle border-r border-outline-variant',
  breakRow: 'bg-primary-fixed/20 border-y-2 border-primary/30',
  breakRowContent: 'py-2 px-4 flex items-center justify-between text-xs',
  lunchRow: 'bg-surface-container-high/60 border-y-2 border-outline-variant',
  lunchRowContent: 'py-2 px-4 flex items-center justify-center text-xs font-bold text-on-surface-variant gap-2',
  eveningRow: 'bg-indigo-50 border-y border-indigo-100',
  
  // Right Sidebar Wrapper
  sidebarWrapper: 'xl:col-span-3 space-y-5',
  
  // Sidebar Card
  sidebarCard: 'bg-surface-container-lowest rounded-2xl border border-outline-variant p-5 shadow-sm space-y-4',
  sidebarCardHeader: 'flex items-start justify-between',
  sidebarCardTitle: 'font-bold text-on-surface text-sm',
  sidebarBadge: 'bg-primary-fixed/40 text-primary px-2 py-0.5 rounded-full text-[11px] font-bold',
  sidebarDesc: 'text-xs text-on-surface-variant leading-relaxed',
  
  // Checklist
  checklistItem: 'flex items-start gap-3 p-3 rounded-xl border border-outline-variant/60 bg-surface hover:bg-surface-container-low transition cursor-pointer',
  checklistItemChecked: 'flex items-start gap-3 p-3 rounded-xl border border-outline-variant/30 bg-surface-container-lowest opacity-70 transition cursor-pointer',
  checkbox: 'mt-0.5 w-4 h-4 rounded border-2 border-outline flex items-center justify-center text-white',
  checkboxChecked: 'mt-0.5 w-4 h-4 rounded border-2 border-primary bg-primary flex items-center justify-center text-white',
  checklistTitle: 'font-semibold text-xs text-on-surface',
  checklistTitleChecked: 'font-semibold text-xs text-on-surface-variant line-through',
  checklistSub: 'text-[11px] text-on-surface-variant mt-0.5',
  addReminderBtn: 'w-full py-2 flex items-center justify-center gap-1.5 bg-surface border border-outline-variant hover:bg-surface-container rounded-lg text-xs font-semibold text-on-surface transition active:scale-95',
  
  // Reminder Toggle
  reminderToggleWrapper: 'flex items-center justify-between p-3 rounded-xl bg-surface border border-outline-variant',
  reminderToggleLeft: 'space-y-0.5',
  reminderToggleTitle: 'font-semibold text-xs text-on-surface',
  reminderToggleSub: 'text-[11px] text-on-surface-variant',
  toggleBg: 'w-9 h-5 bg-primary rounded-full relative flex items-center px-0.5 cursor-pointer',
  toggleKnob: 'w-4 h-4 bg-white rounded-full shadow-sm transform translate-x-4 transition-transform',
  
  reminderNextBox: 'p-3 rounded-xl bg-primary-fixed/20 border border-primary/30 space-y-1.5',
  reminderNextTitle: 'flex items-center gap-1.5 font-semibold text-xs text-primary',
  reminderNextDesc: 'text-[11px] text-on-surface-variant leading-relaxed',
  
  // Upload Card
  uploadCard: 'bg-surface-container-lowest rounded-2xl border border-outline-variant p-6 shadow-sm flex flex-col items-center text-center space-y-3',
  uploadIconWrapper: 'w-12 h-12 rounded-full bg-primary flex items-center justify-center text-white shadow-md',
  uploadTitle: 'font-bold text-sm text-on-surface',
  uploadDesc: 'text-xs text-on-surface-variant leading-relaxed',
  uploadBtn: 'w-full py-2 bg-primary hover:bg-primary-container text-on-primary rounded-lg text-xs font-semibold transition active:scale-95 shadow-sm',
};
