export const styles = {
  layout: 'min-h-screen bg-[#f8fafc] text-[#0f172a] font-sans antialiased flex flex-col selection:bg-[#005cb8]/10 selection:text-[#005cb8]',
  header: 'sticky top-0 z-40 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl shadow-xs transition-all',
  headerInner: 'mx-auto flex h-16 max-w-[1680px] items-center justify-between gap-4 px-4 sm:px-6 lg:px-8',
  brand: 'flex min-w-0 items-center gap-3',
  menuButton: 'grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 transition-all hover:bg-slate-50 hover:text-[#005cb8] hover:border-[#005cb8]/30 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#005cb8] lg:hidden',
  brandMark: 'relative flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-tr from-[#004bb5] to-[#2575fc] text-white shadow-md shadow-[#005cb8]/20 ring-1 ring-white/20',
  brandCopy: 'min-w-0 flex flex-col justify-center',
  brandTitle: 'block truncate text-sm font-bold tracking-tight text-slate-900 sm:text-base flex items-center gap-1.5',
  brandLabel: 'block text-[10px] font-extrabold uppercase tracking-widest leading-none text-[#005cb8] mt-0.5',
  
  headerCenter: 'hidden md:flex items-center gap-3 flex-1 max-w-md mx-6',
  searchBar: 'w-full flex items-center gap-2.5 px-3 py-1.5 rounded-xl border border-slate-200/90 bg-slate-50/70 hover:bg-white hover:border-slate-300 focus-within:bg-white focus-within:border-[#005cb8] focus-within:ring-2 focus-within:ring-[#005cb8]/10 transition-all text-xs text-slate-500',
  searchKbd: 'text-[10px] font-semibold text-slate-400 border border-slate-200 rounded px-1.5 py-0.5 bg-slate-100 ml-auto',

  userArea: 'flex items-center gap-3 sm:gap-4',
  systemStatusBadge: 'hidden sm:inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-50 border border-emerald-200/60 text-emerald-700 text-[11px] font-semibold',
  userCopy: 'hidden text-right sm:flex sm:flex-col sm:justify-center',
  userName: 'block max-w-44 truncate text-xs font-bold text-slate-900',
  userRoleBadge: 'inline-flex items-center justify-end gap-1 text-[10px] font-semibold text-[#005cb8] bg-[#d6e3ff]/70 px-2 py-0.5 rounded-md mt-0.5 self-end',
  avatar: 'grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-[#d6e3ff] to-[#b6d0ff] text-xs font-extrabold text-[#00458d] ring-2 ring-white shadow-xs',
  logoutButton: 'grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 transition-all hover:border-red-200 hover:bg-red-50 hover:text-red-600 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500',
  
  body: 'mx-auto flex w-full max-w-[1680px] flex-1 items-start',
  sidebar: 'sticky top-16 hidden h-[calc(100vh-4rem)] w-64 shrink-0 border-r border-slate-200/80 bg-white/95 backdrop-blur-md px-3.5 py-5 lg:flex lg:flex-col justify-between shadow-[1px_0_4px_rgba(0,0,0,0.02)]',
  mobileBackdrop: 'fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs transition-opacity lg:hidden',
  mobileSidebar: 'fixed inset-y-0 left-0 z-[60] flex w-[min(84vw,288px)] flex-col bg-white px-4 py-5 shadow-2xl lg:hidden justify-between',
  mobileSidebarHeader: 'mb-4 flex items-center justify-between border-b border-slate-100 pb-3 px-1',
  closeButton: 'grid h-8 w-8 place-items-center rounded-lg text-slate-500 transition hover:bg-slate-100 hover:text-slate-900',
  
  navSectionTitle: 'mb-2 px-3 text-[11px] font-bold uppercase tracking-wider text-slate-400',
  navGroup: 'space-y-1 mb-5',
  nav: 'space-y-1',
  navLink: 'group relative flex min-h-10 items-center justify-between rounded-xl px-3 py-2 text-xs font-semibold text-slate-600 transition-all hover:bg-slate-100 hover:text-slate-900',
  navLinkActive: 'group relative flex min-h-10 items-center justify-between rounded-xl bg-[#005cb8]/10 px-3 py-2 text-xs font-bold text-[#005cb8] shadow-2xs before:absolute before:left-0 before:top-2 before:bottom-2 before:w-1 before:rounded-r-md before:bg-[#005cb8]',
  navItemContent: 'flex items-center gap-3 min-w-0',
  navIcon: 'shrink-0 text-slate-400 transition-colors group-hover:text-slate-700',
  navIconActive: 'shrink-0 text-[#005cb8]',
  navBadge: 'inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-500 border border-slate-200/80',
  navBadgeActive: 'inline-flex items-center rounded-full bg-[#005cb8] px-2 py-0.5 text-[10px] font-semibold text-white',
  
  sidebarFooter: 'border-t border-slate-100 px-2 pt-4 text-xs leading-relaxed text-slate-500 space-y-3',
  systemStatusCard: 'rounded-xl bg-gradient-to-br from-slate-50 to-blue-50/50 p-3 border border-slate-200/80 text-[11px] space-y-1.5 shadow-2xs',
  main: 'min-w-0 flex-1 px-4 py-6 sm:px-6 sm:py-8 lg:px-8 xl:px-10',
};
